# Simple workflow for deploying static content to GitHub Pages
name: Build on PR

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  # Single deploy job since we're just deploying
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
      
      - name: Install dependencies
        run: npm install

      - name: Vite Build
        run: npm run build
